version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - errcheck
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        tests:
          deny:
            - pkg: github.com/stretchr/testify/assert
              desc: Use github.com/stretchr/testify/require instead of testify/assert
            - pkg: github.com/onsi/gomega
              desc: Although Ginkgo is used in kubebuilder, use testify instead. Ginkgo is bloated providing little value.
            - pkg: github.com/onsi/ginkgo/v2
              desc: Although Ginkgo is used in kubebuilder, use testify instead. Ginkgo is bloated providing little value.
            - pkg: github.com/onsi/ginkgo
              desc: Although Ginkgo is used in kubebuilder, use testify instead. Ginkgo is bloated providing little value.
    misspell:
      locale: US
      ignore-rules:
        - statuser
    nakedret:
      max-func-lines: 0
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
